version: "3.3"
services:
  csvserver:
    image: infracloudio/csvserver:latest
    container_name: csvserver
    volumes:
     - /home/alind/Desktop/infracloud/infracloud/solution/inputFile:/csvserver/inputdata
    environment:
     CSVSERVER_BORDER: Orange
    ports:
     - "9393:9300"
  prometheus:
    image: prom/prometheus:v2.22.0
    container_name: prometheus
    volumes:
     - /home/alind/Desktop/infracloud/infracloud/solution/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
     - "9090:9090"
    links:
     - csvserver